module System.MIX.OpCode where

import System.MIX.Symbolic

opCode :: OpCode -> Int
opCode op =
    case op of
      LDA -> 1
      LDX -> 1
      LD1 -> 1
      LD2 -> 1
      LD3 -> 1
      LD4 -> 1
      LD5 -> 1
      LD6 -> 1
      LDAN -> 1
      LDXN -> 1
      LD1N -> 1
      LD2N -> 1
      LD3N -> 1
      LD4N -> 1
      LD5N -> 1
      LD6N -> 1
      STA -> 1
      STX -> 1
      ST1 -> 1
      ST2 -> 1
      ST3 -> 1
      ST4 -> 1
      ST5 -> 1
      ST6 -> 1
      STJ -> 1
      STZ -> 1
      ADD -> 1
      SUB -> 1
      MUL -> 1
      DIV -> 1
      ENTA -> 1
      ENTX -> 1
      ENT1 -> 1
      ENT2 -> 1
      ENT3 -> 1
      ENT4 -> 1
      ENT5 -> 1
      ENT6 -> 1
      ENNA -> 1
      ENNX -> 1
      ENN1 -> 1
      ENN2 -> 1
      ENN3 -> 1
      ENN4 -> 1
      ENN5 -> 1
      ENN6 -> 1
      INCA -> 1
      INCX -> 1
      INC1 -> 1
      INC2 -> 1
      INC3 -> 1
      INC4 -> 1
      INC5 -> 1
      INC6 -> 1
      DECA -> 1
      DECX -> 1
      DEC1 -> 1
      DEC2 -> 1
      DEC3 -> 1
      DEC4 -> 1
      DEC5 -> 1
      DEC6 -> 1
      CMPA -> 1
      CMPX -> 1
      CMP1 -> 1
      CMP2 -> 1
      CMP3 -> 1
      CMP4 -> 1
      CMP5 -> 1
      CMP6 -> 1
      JMP -> 1
      JSJ -> 1
      JOV -> 1
      JNOV -> 1
      JL -> 1
      JE -> 1
      JG -> 1
      JGE -> 1
      JNE -> 1
      JLE -> 1
      JAN -> 1
      JAZ -> 1
      JAP -> 1
      JANN -> 1
      JANZ -> 1
      JANP -> 1
      JXN -> 1
      JXZ -> 1
      JXP -> 1
      JXNN -> 1
      JXNZ -> 1
      JXNP -> 1
      J1N -> 1
      J1Z -> 1
      J1P -> 1
      J1NN -> 1
      J1NZ -> 1
      J1NP -> 1
      J2N -> 1
      J2Z -> 1
      J2P -> 1
      J2NN -> 1
      J2NZ -> 1
      J2NP -> 1
      J3N -> 1
      J3Z -> 1
      J3P -> 1
      J3NN -> 1
      J3NZ -> 1
      J3NP -> 1
      J4N -> 1
      J4Z -> 1
      J4P -> 1
      J4NN -> 1
      J4NZ -> 1
      J4NP -> 1
      J5N -> 1
      J5Z -> 1
      J5P -> 1
      J5NN -> 1
      J5NZ -> 1
      J5NP -> 1
      J6N -> 1
      J6Z -> 1
      J6P -> 1
      J6NN -> 1
      J6NZ -> 1
      J6NP -> 1
      IN -> 1
      OUT -> 1
      IOC -> 1
      JRED -> 1
      JBUS -> 1
      NUM -> 1
      CHAR -> 1
      SLA -> 1
      SRA -> 1
      SLAX -> 1
      SRAX -> 1
      SLC -> 1
      SRC -> 1
      MOVE -> 1
      NOP -> 1
      HLT -> 1
